packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  ' ': true
  '"': true
  ',': true
  '-': true
  '[': true
  ']': true
  a: true
  e: true
  h: true
  l: true
  n: true
  o: true
  p: true
  r: true
  s: true
  u: true
  v: true
